### ISSUE TITLE
Issue with PyOpenWorm locking the db.

### ISSUE THREAD

**Issue by jamiebbowen** [joebowen/model_completion_dashboard#7]
[Sun Aug 16 23:11:41 2015] [error] ERROR:zc.lockfile:Error locking file /var/lib/openshift/559fbd50500446f9f10000ca/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/worm.db.lock; pid=219322
[Sun Aug 16 23:11:41 2015] [error] Traceback (most recent call last):
[Sun Aug 16 23:11:41 2015] [error]   File "/var/lib/openshift/559fbd50500446f9f10000ca/python/virtenv/lib/python2.7/site-packages/zc/lockfile/**init**.py", line 84, in **init**
[Sun Aug 16 23:11:41 2015] [error]     _lock_file(fp)
[Sun Aug 16 23:11:41 2015] [error]   File "/var/lib/openshift/559fbd50500446f9f10000ca/python/virtenv/lib/python2.7/site-packages/zc/lockfile/__init__.py", line 59, in _lock_file
[Sun Aug 16 23:11:41 2015] [error]     raise LockError("Couldn't lock %r" % file.name)
[Sun Aug 16 23:11:41 2015] [error] LockError: Couldn't lock '/var/lib/openshift/559fbd50500446f9f10000ca/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/worm.db.lock'

**Comment by jamiebbowen** [comment]
This is caused by simultaneous connections to the website and can cause a condition where the db gets locked until the server is manually reset.
